### ISSUE TITLE
Implement hardware integration harness

### ISSUE THREAD

**Issue by rcheetham** [azavea/coffee-button#5]
Develop resilient attachment harness for button to stainless steel surface. Recommend velcro - it is a reasonable and sturdy solution that is low cost and reversible.

**Comment by kdeloach** [comment]
I have some velcro strips that we could use for this.

**Comment by rcheetham** [comment]
I've got some rolls I've been using for tablets that are pretty tough.

**Comment by rcheetham** [comment]
Joe has recommended:
I would say optimal placement is a 1/2 inch directly below its current location. Right now the top overlaps with the touch screen just a little bit.

**Comment by rcheetham** [comment]
Installed velcro attachment based on additional feedback from @jmorrison1847
